from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


class Database:
    scenarios: Dict[int, str] = {
        1: "black barrow",
        2: "barrow lair",
        3: "inox encampment",
        4: "crypt of the damned",
        5: "ruinous crypt",
        6: "decaying crypt",
        7: "vibrant grotto",
        8: "gloomhaven warehouse",
        9: "diamond mine",
        10: "plane of elemental power",
        11: "gloomhaven square a",
        12: "gloomhaven square b",
        13: "temple of the seer",
        14: "frozen hollow",
        15: "shrine of strength",
        16: "mountain pass",
        17: "lost island",
        18: "abandoned sewers",
        19: "forgotten crypt",
        20: "necromancer's sanctum",
        21: "infernal throne",
        22: "temple of the elements",
        23: "deep ruins",
        24: "echo chamber",
        25: "icecrag ascent",
        26: "ancient cistern",
        27: "ruinous rift",
        28: "outer ritual chamber",
        29: "sanctuary of gloom",
        30: "shrine of the depths",
        31: "plane of night",
        32: "decrepit wood",
        33: "savvas armory",
        34: "scorched summit",
        35: "gloomhaven battlements a",
        36: "gloomhaven battlements b",
        37: "doom trench",
        38: "slave pens",
        39: "treacherous divide",
        40: "ancient defense network",
        41: "timeworn tomb",
        42: "realm of the voice",
        43: "drake nest",
        44: "tribal assault",
        45: "rebel swamp",
        46: "nightmare peak",
        47: "lair of the unseeing eye",
        48: "shadow weald",
        49: "rebel's stand",
        50: "ghost fortress",
        51: "the void",
        52: "noxious cellar",
        53: "crypt basement",
        54: "palace of ice",
        55: "foggy thicket",
        56: "bandit's wood",
        57: "investigation",
        58: "bloody shack",
        59: "forgotten grove",
        60: "alchemy lab",
        61: "fading lighthouse",
        62: "pit of souls",
        63: "magma pit",
        64: "underwater lagoon",
        65: "sulfur mine",
        66: "clockwork cove",
        67: "arcane library",
        68: "toxic moor",
        69: "well of the unfortunate",
        70: "chained isle",
        71: "windswept highlands",
        72: "oozing grove",
        73: "rockslide ridge",
        74: "merchant ship",
        75: "overgrown graveyard",
        76: "harrower hive",
        77: "vault of secrets",
        78: "sacrifice pit",
        79: "lost temple",
        80: "vigil keep",
        81: "temple of the eclipse",
        82: "burning mountain",
        83: "shadows within",
        84: "crystalline cave",
        85: "sun temple",
        86: "harried village",
        87: "corrupted cove",
        88: "plane of water",
        89: "syndicate hideout",
        90: "demonic rift",
        91: "wild melee",
        92: "back alley brawl",
        93: "sunken vessel",
        94: "vermling nest",
        95: "payment due",
    }
    blockers: Dict[int, List[Tuple[int, Optional[str]]]] = {
        8: [(3, None), (9, None)],
        9: [(8, None)],
        11: [(12, None), (45, "if 35 done"), (49, "if 35 done"), (50, "if 35 done")],
        12: [(11, None)],
        21: [(35, None), (36, None)],
        25: [(34, "if 33 done")],
        27: [(10, None), (21, None), (35, None), (36, None)],
        34: [(33, None)],
        35: [(27, "if 21 not done"), (31, "if 21 not done"), (36, None)],
        36: [(10, None), (21, None), (35, None)],
        41: [(42, None)],
        42: [(32, None), (33, None), (40, None), (41, None)],
        45: [(11, None), (35, None)],
        49: [(50, None)],
        50: [(49, None)],
    }
